bin/dvm.js
registry url `url_prefix` in registries.json ends with `/`, no more slash need before `v` as below:
```js
`${url_prefix}v${version}/${name}`
```
=> fix: double slash in download url

bin/dvm.js
ref: https://github.com/justjavac/dvm/issues/16
The fix essentially does two things:
1) fix the package names to comply with the latest release package names
2) default to deno instead of denocn as the registry
This will resolve the bug mentioned beloe
=> fix bug where latest versions are not downloading

bin/dvm.js
added necessary options to rmdirSync for macos
=> fix: missing options prevent directory deletion

src/utils.rs
dvm root is hardcoded to `$HOME/.dvm` , this PR makes it configurable with the `DVM_DIR` environment variable.
=> feat: Support changing dvm root by DVM_DIR env

src/commands/install.rs
This commit is intended to get the ball rolling to support Apple M1.
Related issue: #51
=> Detect aarch64 to support Apple M1

src/commands/list.rs
before
after
this pr makes more recent versions more close to current prompt line
=> chore: change list-remote sorting from descending to ascending

Cargo.lock, Cargo.toml, src/commands/install.rs, src/commands/uninstall.rs, src/commands/use_version.rs, src/main.rs, src/meta.rs, src/utils.rs
this refactors utilizing `set_env` to prepends dvm bin path ahead of any other deno path in PATH to make it the `default deno executable`.
now `dvm use` will not replace the global one anymore
this pr will make `activate` and `deactivate` command possible
Fixed: #29
=> refactor: use command now use hardlink instead of copying and more

src/commands/doctor.rs, src/commands/install.rs, src/consts.rs, src/meta.rs, src/utils.rs
=> fix #87: `Lacking the presence of the new cache folder will making DVM doctor command crash`

.github/workflows/ci.yml, install.sh
The PR #89 broke `install.sh` script on MacOS for all CPU architectures. This PR fixes that break and adds test to ensure it doesn't happen in the future.
1. #89
2. #51
1. Fix script issue causing installations to fail on MacOS in `install.sh`.
3. Changed OS+CPU logic to gracefully error in cases of unsupported combinations in `install.sh`.
4. Allowed for `install.sh` to receive an optional argument for installation from a local copy of dvm for easy testing.
5. Updated CI to test that `install.sh` works on MacOS and Linux, via changes in `.github/workflows/ci.yml`.
=> Fixed MacOS install and added test

src/commands/activate.rs, src/commands/doctor.rs, src/commands/install.rs, src/commands/use_version.rs, src/main.rs, src/meta.rs, src/utils.rs
This PR added a `--local` flag to the `use` command to tell DVM to write the version metadata to the config file in the current directory.
=> feat. adding --local flag to `use` command

src/commands/install.rs, src/commands/use_version.rs, src/consts.rs, src/utils.rs, src/version.rs
This PR makes `use` command and `install` command recognized canary as a version
Closed: #80
=> feat. canary

Cargo.lock, Cargo.toml
Upgrading semver v1.0.9 -> v1.0.12
Upgrading clap v3.1.18 -> v3.2.8
Upgrading serde v1.0.137 -> v1.0.138
Upgrading anyhow v1.0.57 -> v1.0.58
Upgrading clap_complete v3.1.4 -> v3.2.3
Upgrading clap_derive v3.1.18 -> v3.2.7
Upgrading serde_json v1.0.81 -> v1.0.82
=> cargo upgrade

src/commands/exec.rs, src/commands/install.rs, src/commands/mod.rs, src/commands/registry.rs, src/commands/upgrade.rs, src/commands/use_version.rs, src/main.rs
This PR adds a new command `registry`
use cases
```bash
dvm registry official # or leave blank to set the registry to the official one (https://dl.deno.land/)
dvm registry cn # set the registry to https://dl.deno.js.cn/
dvm registry [URL] # set the registry to custom url
```
=> feat: registry

src/commands/uninstall.rs
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/commands/uninstall.rs:35:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> fix(uninstall): panic "No such file or directory"

src/commands/alias.rs
在设置别名之前，检查下用户输入的内容是否符合semver规范，不符合则抛出异常。
=> opt: check whether the alias content is  valid before setting it

src/commands/alias.rs, src/version.rs
执行alias list 时，打印信息补充符合semver规则的可更新版本
=> optimize(alias list): Adding upgrade version

Cargo.lock, Cargo.toml, src/cli.rs, src/commands/alias.rs, src/commands/exec.rs, src/commands/install.rs, src/commands/registry.rs, src/commands/use_version.rs, src/configrc.rs, src/consts.rs, src/main.rs, src/meta.rs, src/utils.rs, src/version.rs
* registry command refactor
* internal refactor about how registry was stored
* add `--write-local` or `-L` flags to `use` command and `registry set`
* remove registry autochange by auto detect user's locale language
* unify `version registry` format (different between `official` and `cn` before)
* and more
```rc
registry_binary=https://dl.deno.land/
registry_version=https://raw.githubusercontent.com/denoland/dotland/main/versions.json
deno_version=latest
```
=> refactor: dvm command `registry`

install.ps1
Added because it throws an ItemNotFoundException when the file doesn't exists
=> Add SilentlyContinue error action.

install.ps1, main.ts
- Add `-ErrorAction SilentlyContinue` to `Rename-Item` to avoid first-time installation failures.
- Update to reflect changes in PowerShell user agent since PowerShell 6
- https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.3#-useragent
=> Fix PowerShell installation issues

src/commands/install.rs, src/commands/registry.rs, src/commands/use_version.rs, src/configrc.rs, src/utils.rs, src/version.rs
Try to ensure the user set the right configuration.
=> chore: enable to fix the missing property when failed to get it from the config rc

install.sh
The install script currently breaks `.bash_profile` if it doesn't end with a trailing newline.
For example:
```
ulimit -n 8192
```
becomes
```
ulimit -n 8192export DVM_DIR="..."
```
=> ensure leading newline when adding lines to shell profile

.cargo/config.toml, .github/workflows/ci.yml, install.sh, src/commands/install.rs
=> add support for linux aarch64
