README.md, bin/dvm.js
TODO 
``` js
.option("-r, --registry <source>", "source registry") // <==
.action(function(version, cmd) { // <==
I("check whether the current version is installed");
if (fs.existsSync(path.join(DVM_PATH, version))) {
console.log(
"Deno v%s is already installed, run `dvm use %s` to use this version.",
version,
version
);
process.exit(1);
}
I("deno v%s is not installed", version);
I("try to download version:%s, registry:%s", version, cmd.registry); // <==
download(version, cmd.registry) //<==
```
=> Add: TODO dvm install x.x.x -r denocn

package.json, yarn.lock
=> Resole security alert

CHANGELOG.md, package.json
=> Release v0.3.1

package.json, yarn.lock
=> resolve security

src/commands/use_.rs
=> Fix dir not exists

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release v1.1.9

Cargo.lock, src/commands/info.rs, src/commands/install.rs
=> feat: use `dl.deno.land`

install.sh
=> support arm64 architecture

.gitignore, src/commands/use_.rs, src/version.rs
=> use .dvmrc

Cargo.lock, Cargo.toml, src/commands/alias.rs, src/commands/mod.rs, src/commands/use_version.rs, src/main.rs, src/meta.rs, src/utils.rs
* dvm alias set <name> <required verison>
* dvm alias unset <name>
* dvm alias list
Default alias is only latest -> * for now. deno seems don't have stable or beta? for now.
Closes #49
=> feat. alias command

.gitignore, src/commands/use_version.rs
This pr is for consistent behavior of the `upgrade` command
=> `use` command will reject for using semverrange directly now

Cargo.lock, Cargo.toml, src/commands/activate.rs, src/commands/deactivate.rs, src/commands/mod.rs, src/main.rs, src/utils.rs
Adding `activate` and `deactivate` command
=> Feat. deactivate

src/commands/doctor.rs, src/commands/install.rs, src/commands/mod.rs, src/commands/use_version.rs, src/main.rs
Fixing dvm specific environment variables and other issues
=> feat. doctor command

Cargo.lock, Cargo.toml
=> upgrade set-env to 1.3.0

src/commands/install.rs, src/commands/mod.rs, src/commands/upgrade.rs, src/main.rs, src/meta.rs
This PR added an upgrade command for upgrading aliases
Fixed: #63
=> feat. upgrade

src/commands/exec.rs, src/commands/mod.rs, src/commands/use_version.rs, src/main.rs, src/utils.rs
This PR added an `exec` command for executes deno commands with specific deno version
=> feat. exec

src/commands/clean.rs, src/commands/mod.rs, src/consts.rs, src/main.rs, src/meta.rs
This PR added a `clean` command for cleaning outdated cache files
=> feat. clean

src/commands/install.rs, src/commands/upgrade.rs
This PR makes `upgrade` command recognize `canary` and can upgrade canary unconditionally
=> feat. upgrade canary

Cargo.toml
=> add author cgqaq

Cargo.lock, Cargo.toml
=> compile and statically link to OpenSSL

src/commands/deactivate.rs, src/commands/use_version.rs
=> feat(use): system alias

install.ps1, install.sh
=> chores(install-scripts): remove unused env vars #127

src/main.rs
=> optimize: command exec args

README.md, README_zh-cn.md, src/commands/clean.rs, src/commands/doctor.rs, src/configrc.rs
* update README
* cleanup dvmrc in `doctor` command
=> fix: update failed when local dvmrc file not exists

README.md, README_zh-cn.md, install.ps1, src/cli.rs, src/commands/upgrade.rs, src/consts.rs
🎉  dvm now can finally upgrade itself
=> feat: upgrade self

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/commands/install.rs
=> fix Intel Macs
